### ISSUE TITLE
文件移动有问题

### ISSUE THREAD

**Issue by SettingDust** [BalloonUpdate/McPatchManage#3]
history 里面的文件没了，而且 history 文件夹应该已经被打乱了= =
```
Exception in thread "main" java.io.FileNotFoundException: H:/Minecraft/**/**1/更新补丁/history/.minecraft/versions/**1/config/paxi/datapacks/towns-and-towers-structure-overhaul-terralith-1-6/data/kaisyn/structures/village/exclusives/mediterranean/houses/regular/house_1.nbt
        at mcpatch.utils.File2.move(File2.kt:115)
        at mcpatch.diff.RealFile.syncFrom(RealFile.kt:25)
        at mcpatch.interactive.Create.create(Create.kt:283)
        at mcpatch.interactive.Create.execute(Create.kt:309)
        at mcpatch.McPatchManage.main(McPatchManage.kt:59)
```

EDIT
---

没有旧文件，但是目录全部识别成旧目录，应该是被先删掉了
![图片](https://github.com/BalloonUpdate/McPatchManage/assets/19922286/f878411d-9ba2-4a3b-b180-4f180caa1442)

**Comment by asforest** [comment]
要如何复现？这个问题

**Comment by SettingDust** [comment]
每次出现都会导致 history 废掉，没办法知道具体情况

**Comment by asforest** [comment]
尝试缩短文件路径看看，尽量不要使文件的绝对路径超过255个字节长度

**Comment by SettingDust** [comment]
> 尝试缩短文件路径看看，尽量不要使文件的绝对路径超过255个字节长度

不太可能做到

我复现了
EDIT: 更简单就能复现
[复现.zip](https://github.com/BalloonUpdate/McPatchManage/files/11494486/default.zip)

```ps1
rm -r -fo workspace
rm -r -fo public
rm -r -fo history

New-Item -ItemType File -Path workspace/parent/a/a -Force
New-Item -ItemType File -Path workspace/parent/b/a -Force

java -jar .\McPatchManage-1.1.6.jar c 0.1.0 y q
Move-Item -Path 'workspace/parent' -Destination 'workspace/bug'

java -jar .\McPatchManage-1.1.6.jar c 0.1.1 y q
```

**Comment by asforest** [comment]
问题原因找到了，当两个同名文件的内容相同时就会触发这个问题。一会发布1.1.7版本会修复这个问题

**Comment by SettingDust** [comment]
https://github.com/BalloonUpdate/McPatchManage/commit/62890afcf9f6dd90f9c991726161d39e98a4212e
